services:

  mysql:
    image: mysql:8.0
    container_name: main_cal_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calorie_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  auth-service:
    build: ./Cal_Track
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  calorie-service:
    build: ./Calorie-Service
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  api-gateway:
    build: ./Api-Gateway-Service
    ports:
      - "8080:8080"
    depends_on:
      - calorie-service
      - auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always

volumes:
  mysql_data:
